### ISSUE TITLE
Having trouble deploying to Heroku

### ISSUE THREAD

**Issue by chintanparikh** [vigetlabs/gulp-rails-pipeline#38]
Hi,

So I tried to deploy to heroku following the instructions specified, but got the following error:

```
Counting objects: 667, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (470/470), done.
Writing objects: 100% (667/667), 344.58 KiB | 0 bytes/s, done.
Total 667 (delta 278), reused 392 (delta 148)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/ddollar/heroku-buildpack-multi.git... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.10.36
remote:        engines.npm (package.json):   2.3.0
remote:
remote:        Downloading and installing node 0.10.36...
remote:        Downloading and installing npm 2.3.0 (replacing version 1.4.28)...
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > optipng-bin@0.3.11 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
remote:        > node index.js
remote:
remote:        ✔ pre-build test passed successfully!
remote:
remote:        > gifsicle@0.1.7 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
remote:        > node index.js
remote:
remote:        ✔ pre-build test passed successfully!
remote:
remote:        > jpegtran-bin@0.2.8 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
remote:        > node index.js
remote:
remote:        ✔ pre-build test passed successfully!
remote:
remote:        > pngquant-bin@0.3.5 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
remote:        > node index.js
remote:
remote:        ✔ pre-build test passed successfully!
remote:
remote:        > utf-8-validate@1.2.1 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
remote:        CXX(target) Release/obj.target/validation/src/validation.o
remote:        SOLINK_MODULE(target) Release/obj.target/validation.node
remote:        SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
remote:        COPY Release/validation.node
remote:        make: Leaving directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
remote:
remote:        > bufferutil@1.2.1 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
remote:        CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
remote:        SOLINK_MODULE(target) Release/obj.target/bufferutil.node
remote:        SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
remote:        COPY Release/bufferutil.node
remote:        make: Leaving directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
remote:
remote:        > bufferutil@1.2.1 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
remote:        CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
remote:        SOLINK_MODULE(target) Release/obj.target/bufferutil.node
remote:        SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
remote:        COPY Release/bufferutil.node
remote:        make: Leaving directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
remote:
remote:        > utf-8-validate@1.2.1 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
remote:        CXX(target) Release/obj.target/validation/src/validation.o
remote:        SOLINK_MODULE(target) Release/obj.target/validation.node
remote:        SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
remote:        COPY Release/validation.node
remote:        make: Leaving directory `/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
remote:
remote:        > spawn-sync@1.0.14 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
remote:        > node postinstall
remote:
remote:        Installing native dependencies (this may take up to a minute)
remote:
remote:        > node-sass@3.4.2 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-sass/node_modules/node-sass
remote:        > node scripts/install.js
remote:
remote:        Binary downloaded and installed at /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node
remote:
remote:        > node-sass@3.4.2 postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-sass/node_modules/node-sass
remote:        > node scripts/build.js
remote:
remote:        ` /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists.
remote:        testing binary.
remote:        Binary is fine; exiting.
remote:
remote:        > ttf2woff2@1.2.3 install /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
remote:        > (node-gyp rebuild > builderror.log) || (exit 0)
remote:
remote:        ../csrc/addon.cc:9:20: error: ‘FunctionCallbackInfo’ does not name a type
remote:        void Convert(const FunctionCallbackInfo<Value>& args) {
remote:        ^
remote:        ../csrc/addon.cc:9:20: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
remote:        ../csrc/addon.cc:9:40: error: expected ‘,’ or ‘...’ before ‘<’ token
remote:        void Convert(const FunctionCallbackInfo<Value>& args) {
remote:        ^
remote:        ../csrc/addon.cc: In function ‘void Convert(int)’:
remote:        ../csrc/addon.cc:11:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
remote:        HandleScope scope(isolate);
remote:        ^
remote:        ../csrc/addon.cc:11:28: note: candidates are:
remote:        In file included from /app/.node-gyp/0.10.36/src/node.h:62:0,
remote:        from ../csrc/addon.cc:1:
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
remote:        HandleScope(const HandleScope&);
remote:        ^
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
remote:        HandleScope();
remote:        ^
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
remote:        ../csrc/addon.cc:13:7: error: ‘args’ was not declared in this scope
remote:        if (args.Length() < 1) {
remote:        ^
remote:        ../csrc/addon.cc:14:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
remote:        isolate->ThrowException(Exception::TypeError(
remote:        ^
remote:        ../csrc/addon.cc:15:9: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
remote:        String::NewFromUtf8(isolate, "Wrong number of arguments")));
remote:        ^
remote:        ../csrc/addon.cc:19:8: error: ‘args’ was not declared in this scope
remote:        if (!args[0]->IsObject()) {
remote:        ^
remote:        ../csrc/addon.cc:20:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
remote:        isolate->ThrowException(Exception::TypeError(
remote:        ^
remote:        ../csrc/addon.cc:21:9: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
remote:        String::NewFromUtf8(isolate, "Not an object")));
remote:        ^
remote:        ../csrc/addon.cc:25:31: error: ‘args’ was not declared in this scope
remote:        Local<Object> inputBuffer = args[0]->ToObject();
remote:        ^
remote:        ../csrc/addon.cc:28:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
remote:        isolate->ThrowException(Exception::TypeError(
remote:        ^
remote:        ../csrc/addon.cc:29:9: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
remote:        String::NewFromUtf8(isolate, "First arg should be a Buffer")));
remote:        ^
remote:        ../csrc/addon.cc:45:14: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
remote:        isolate->ThrowException(Exception::TypeError(
remote:        ^
remote:        ../csrc/addon.cc:46:9: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
remote:        String::NewFromUtf8(isolate, "Could not convert the given font.")));
remote:        ^
remote:        ../csrc/addon.cc:49:70: error: no matching function for call to ‘node::Buffer::New(v8::Isolate*&, size_t&)’
remote:        Local<Object> slowBuffer = node::Buffer::New(isolate, output_length);
remote:        ^
remote:        ../csrc/addon.cc:49:70: note: candidates are:
remote:        In file included from ../csrc/addon.cc:2:0:
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:116:33: note: static v8::Handle<v8::Object> node::Buffer::New(v8::Handle<v8::String>)
remote:        static v8::Handle<v8::Object> New(v8::Handle<v8::String> string);
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:116:33: note:   candidate expects 1 argument, 2 provided
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:121:18: note: static node::Buffer* node::Buffer::New(size_t)
remote:        static Buffer* New(size_t length);
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:121:18: note:   candidate expects 1 argument, 2 provided
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:123:18: note: static node::Buffer* node::Buffer::New(const char*, size_t)
remote:        static Buffer* New(const char *data, size_t len);
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:123:18: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const char*’
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:125:18: note: static node::Buffer* node::Buffer::New(char*, size_t, node::Buffer::free_callback, void*)
remote:        static Buffer* New(char *data, size_t length,
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:125:18: note:   candidate expects 4 arguments, 2 provided
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:129:32: note: static v8::Handle<v8::Value> node::Buffer::New(const v8::Arguments&)
remote:        static v8::Handle<v8::Value> New(const v8::Arguments &args);
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node_buffer.h:129:32: note:   candidate expects 1 argument, 2 provided
remote:        ../csrc/addon.cc:52:38: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’
remote:        Local<Object> globalObj = isolate->GetCurrentContext()->Global();
remote:        ^
remote:        ../csrc/addon.cc:54:42: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
remote:        Local<Function>::Cast(globalObj->Get(String::NewFromUtf8(isolate, "Buffer")));
remote:        ^
remote:        ../csrc/addon.cc:57:57: error: no matching function for call to ‘v8::Number::New(v8::Isolate*&, int)’
remote:        Number::New(isolate, static_cast<int>(output_length)),
remote:        ^
remote:        ../csrc/addon.cc:57:57: note: candidate is:
remote:        In file included from /app/.node-gyp/0.10.36/src/node.h:62:0,
remote:        from ../csrc/addon.cc:1:
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:1381:33: note: static v8::Local<v8::Number> v8::Number::New(double)
remote:        V8EXPORT static Local<Number> New(double value);
remote:        ^
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:1381:33: note:   candidate expects 1 argument, 2 provided
remote:        ../csrc/addon.cc:58:27: error: no matching function for call to ‘v8::Number::New(v8::Isolate*&, int)’
remote:        Number::New(isolate, 0)
remote:        ^
remote:        ../csrc/addon.cc:58:27: note: candidate is:
remote:        In file included from /app/.node-gyp/0.10.36/src/node.h:62:0,
remote:        from ../csrc/addon.cc:1:
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:1381:33: note: static v8::Local<v8::Number> v8::Number::New(double)
remote:        V8EXPORT static Local<Number> New(double value);
remote:        ^
remote:        /app/.node-gyp/0.10.36/deps/v8/include/v8.h:1381:33: note:   candidate expects 1 argument, 2 provided
remote:        ../csrc/addon.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
remote:        ../csrc/addon.cc:65:46: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [8], void (&)(int))’
remote:        NODE_SET_METHOD(exports, "convert", Convert);
remote:        ^
remote:        ../csrc/addon.cc:65:46: note: candidate is:
remote:        In file included from ../csrc/addon.cc:1:0:
remote:        /app/.node-gyp/0.10.36/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
remote:        void SetMethod(target_t obj, const char* name,
remote:        ^
remote:        /app/.node-gyp/0.10.36/src/node.h:112:6: note:   template argument deduction/substitution failed:
remote:        ../csrc/addon.cc:65:46: note:   cannot convert ‘Convert’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
remote:        NODE_SET_METHOD(exports, "convert", Convert);
remote:        ^
remote:        make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
remote:        gyp ERR! System Linux 3.13.0-66-generic
remote:        gyp ERR! command "node" "/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
remote:        gyp ERR! node -v v0.10.36
remote:        gyp ERR! node-gyp -v v1.0.2
remote:        gyp ERR! not ok
remote:
remote:        > gulp-rails@ postinstall /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf
remote:        > gulp build
remote:
remote:
remote:        /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
remote:        aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
remote:        ^
remote:        Error: Cannot find module 'gulp-watch'
remote:        at Function.Module._resolveFilename (module.js:338:15)
remote:        at Function.Module._load (module.js:280:25)
remote:        at Module.require (module.js:364:17)
remote:        at require (module.js:380:17)
remote:        at Object.<anonymous> (/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/gulp/tasks/watch.js:8:14)
remote:        at Module._compile (module.js:456:26)
remote:        at Object.Module._extensions..js (module.js:474:10)
remote:        at Module.load (module.js:356:32)
remote:        at Function.Module._load (module.js:312:12)
remote:        at Module.require (module.js:364:17)
remote:
remote:        npm ERR! Linux 3.13.0-66-generic
remote:        npm ERR! argv "node" "/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/.npmrc"
remote:        npm ERR! node v0.10.36
remote:        npm ERR! npm  v2.3.0
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! gulp-rails@ postinstall: `gulp build`
remote:        npm ERR! Exit status 7
remote:        npm ERR!
remote:        npm ERR! Failed at the gulp-rails@ postinstall script 'gulp build'.
remote:        npm ERR! This is most likely a problem with the gulp-rails package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     gulp build
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls gulp-rails
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_fee504646fcf321c4eaf1bbb5a745bbf/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:
remote:  !     Push rejected, failed to compile Multipack app
remote:
remote: Verifying deploy...
remote:
remote: !   Push rejected to seedfeed-production.
remote:
To git@heroku.com:seedfeed-production.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:seedfeed-production.git'
```

**Comment by mavericohm** [comment]
Hi @chintanparikh. How did you solved this issue?

**Comment by chintanparikh** [comment]
I just removed gulp-iconfont and everything related to it because I didn't need it in my project.

**Comment by greypants** [comment]
I've been thinking about dropping the icon-font task. I've been using SVG sprites instead for a while now, and think that's a better way forward.
