### ISSUE TITLE
Can't redeploy to Heroku

### ISSUE THREAD

**Issue by chintanparikh** [vigetlabs/gulp-rails-pipeline#39]
So after a lot of work, I finally got this deployed to Heroku.

However, now when I try to re-deploy after making some changes, I get the following error:

```
± git push production master
Counting objects: 29, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (19/19), 1.61 KiB | 0 bytes/s, done.
Total 19 (delta 15), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/ddollar/heroku-buildpack-multi.git... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.12.7
remote:        engines.npm (package.json):   2.14.4
remote:
remote:        Downloading and installing node 0.12.7...
remote:        Downloading and installing npm 2.14.4 (replacing version 2.11.3)...
remote:
remote: -----> Restoring cache
remote:        Loading 2 from cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > gulp-rails@ postinstall /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c
remote:        > gulp build
remote:
remote:        [06:10:31] Using gulpfile /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/gulpfile.js
remote:        [06:10:31] Starting 'build'...
remote:        [06:10:31] Starting 'clean'...
remote:        [06:10:31] Finished 'clean' after 6.91 ms
remote:        [06:10:31] Starting 'iconFont'...
remote:        [06:10:31] Starting 'images'...
remote:        [06:10:31] gulp-svgicons2svgfont: Font created
remote:        [06:10:32] Finished 'iconFont' after 432 ms
remote:        [06:10:32] gulp-imagemin: Minified 9 images (saved 25.43 kB - 8.9%)
remote:        [06:10:32] Finished 'images' after 1.01 s
remote:        [06:10:32] Starting 'sass'...
remote:        [06:10:32] Starting 'browserify'...
remote:        [06:10:32] Bundling global.js...
remote:        [06:10:32] Finished 'sass' after 285 ms
remote:        [06:10:36] Bundled global.js in 3.81 s
remote:        [06:10:36] Finished 'browserify' after 3.83 s
remote:        [06:10:36] Starting 'rev-assets'...
remote:        [06:10:36] Finished 'rev-assets' after 40 ms
remote:        [06:10:36] Starting 'rev-font-workaround'...
remote:        [06:10:36] 'rev-font-workaround' errored after 640 μs
remote:        [06:10:36] TypeError: Cannot read property 'split' of undefined
remote:        at /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/gulp/tasks/rev/rev-font-workaround.js:30:42
remote:        at forOwn (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/lodash/dist/lodash.js:2106:15)
remote:        at Function.forEach (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/lodash/dist/lodash.js:3303:9)
remote:        at Gulp.<anonymous> (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/gulp/tasks/rev/rev-font-workaround.js:25:5)
remote:        at module.exports (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
remote:        at Gulp.Orchestrator._runTask (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
remote:        at Gulp.Orchestrator._runStep (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
remote:        at /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/index.js:279:18
remote:        at finish (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
remote:        at /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
remote:        at f (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
remote:        at DestroyableTransform.onend (/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
remote:        at DestroyableTransform.emit (events.js:129:20)
remote:        at /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
remote:        at process._tickCallback (node.js:355:11)
remote:
remote:
remote:        npm ERR! Linux 3.13.0-66-generic
remote:        npm ERR! argv "node" "/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/.npmrc"
remote:        npm ERR! node v0.12.7
remote:        npm ERR! npm  v2.14.4
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! gulp-rails@ postinstall: `gulp build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the gulp-rails@ postinstall script 'gulp build'.
remote:        npm ERR! This is most likely a problem with the gulp-rails package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     gulp build
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls gulp-rails
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_a04984ffdd9d47cbfa3be2e3dd43541c/npm-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:
remote:  !     Push rejected, failed to compile Multipack app
remote:
remote: Verifying deploy...
remote:
remote: !   Push rejected to seedfeed-production.
remote:
To git@heroku.com:seedfeed-production.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:seedfeed-production.git'
```

Anyone know what's going on?

**Comment by greypants** [comment]
Hm... seems like `config.iconFont.dest` is undefined. If you're not using an iconFont, you can remove 'rev-font-workaround' from the rev tasks in gulp/tasks/rev.

This repo is getting a little behind... if you want to try and integrate the latest version of [gulp-starter](https://github.com/vigetlabs/gulp-starter), which this was based on, I _just_ merged in some updated rails helpers and a README here: https://github.com/vigetlabs/gulp-starter/tree/master/gulpfile.js/extras/rails

It's on my to-do list to get this repo up to date.
